- front/src/App.tsx
- front/src/components/common/Nav.tsx
- front/src/pages/Profile/FriendList.tsx
- front/src/pages/Profile/ProfileComponent.tsx
- front/src/pages/Profile/ProfileLoader.tsx
- front/src/pages/Profile/ProfilePage.tsx
> [Feat/#4] ProfilePage 기본틀 생성

- front/src/pages/LocalGame/LocalGame.tsx
- nginx/default.conf
> [Feat/#6] wss 보안 설정

- back/vault/Dockerfile
- back/vault/tools/setup.sh
- back/volumes/vault/config/local.json
- docker-compose.yaml
***
***
- 키를 저장할 정보를 파일에 담지 못해서 어려움을 겪고 있었는데 파일을 생성하는 출력 리디렉션은 부모 디렉토리가 없으면 생성하지 않는것을 모르고 있었다.
> [Setting/#3] Vault 컨테이너 생성

- back/accounts/admin.py
- back/accounts/apps.py
- back/accounts/consumers.py
- back/accounts/managers.py
- back/accounts/models.py
- back/accounts/routing.py
- back/accounts/serializers.py
- back/accounts/tests.py
- back/accounts/urls.py
- back/accounts/views.py
- back/transcendence/settings.py
- back/transcendence/urls.py
> [Feat/#14] accounts 기본 생성

- back/accounts/models.py
- back/requirements.txt
> [Fix/#16] account 관련 에러 수정

- back/accounts/managers.py
- back/accounts/models.py
- back/accounts/routing.py
- back/accounts/serializers.py
- back/accounts/urls.py
- back/accounts/utils.py
- back/accounts/views.py
- back/transcendence/asgi.py
- back/transcendence/settings.py
- front/package-lock.json
- front/package.json
- front/src/components/layout/AuthLayout.tsx
- front/src/context/AuthContext.ts
- front/src/hooks/useAuth.tsx
- front/src/pages/Sign/LoginPage.tsx
- front/src/pages/Sign/RegisterPage.tsx
- front/src/providers/AuthProvider.tsx
- front/src/providers/AuthProviderLoader.ts
- front/src/utils/axiosInstace.tsx
- nginx/default.conf
***
register, login 기능 구현
email인증이 지금은 필요없으므로 user model의 is_verified를 True로 설정
***
> [Feat/#18] register, login 구현

- back/accounts/serializers.py
- front/src/App.tsx
- front/src/components/common/SocialLoginButton.tsx
- front/src/loaders/SocialLoginLoader.tsx
- front/src/main.tsx
- front/src/pages/Sign/LoginPage.tsx
> [Feat/#24] SocialLogin Button 추가

- front/src/App.tsx
- front/src/components/common/Nav.tsx
- front/src/context/LangContext.tsx
- front/src/utils/language.ts
***
***
- 다국어 기능 사용 방법 예시 Nav.tsx에 구현
- 필요한 import 후 const { lang } = useLang();
- 다국어 필요한 msg에 language[lang].msg 형태로 사용
> feat/#35 : 다국어 기능 추가

- back/localgame/consumers.py
- front/src/pages/LocalGame/Ball.tsx
- front/src/pages/LocalGame/LocalGame.tsx
- front/src/pages/LocalGame/LocalGamePaddle.tsx
- front/src/pages/LocalGame/LocalGameStyles.css
> [Fix/#41] pong 게임 수치조정

- new_front/src/page/dashboard_related/dashboard.js
- new_front/src/page/dashboard_related/greetingBox.js
- new_front/src/page/dashboard_related/matchHistory.js
- new_front/src/page/dashboard_related/profileAccordion.js
- new_front/src/utils/accordionIconHandler.js
- new_front/styles/matchHistoryAccordion.css
- new_front/styles/profileAccordion.css
> [Fix/#71] 프론트 리팩토링(2.2) - 대시보드 Match History

- new_front/src/app.js
- new_front/src/page/changePassword.js
- new_front/src/page/dashboard_related/profileAccordion.js
- new_front/src/page/editProfile.js
- new_front/styles/Global.css
- new_front/styles/changePassword.css
- new_front/styles/editProfile.css
> [Feat] 대시보드-프로필 아코디언) 비밀번호 변경 페이지 생성 및 스타일 적용

- new_front/index.html
- new_front/src/page/login.js
- new_front/src/page/register.js
- new_front/src/vault.js
- new_front/styles/login.css
***
***
- 기존 js 코드 온전히 유지
- 페이지 렌더링을 위해서 vault.js 주석처리 코드 추가
> [Feat] 로그인 페이지 스타일 수정 & 버튼 링크 연동

- back/social_accounts/utils.py
- back/transcendence/urls.py
- docker-compose.yaml
- nginx/Dockerfile
- nginx/conf/modsec.conf
- nginx/conf/nginx.conf
- nginx/test
- vault/tools/backrole.sh
- vault/tools/frontrole.sh
***
-> 403 FORBIDDEN 페이지 반환
***
curl -k "https://localhost?input=<img src=x onerror=alert('XSS')>"
-> curl -k "https://localhost?input=javascript%3Aalert%28%27XSS%27%29"
curl -k "https://localhost?input=javascript:alert('XSS')"
curl -k "https://localhost?user=admin' -- "
-> curl -k "https://localhost?user=admin%27%20--%20"
curl -k "https://localhost?user=admin' OR '1'='1"
-> curl -k "https://localhost?user=admin%27%20OR%20%271%27%3D%271" 
등등의 명령어를 실행하여 공격이 차단됨을 확인할 수 있음
> Feat/#27 SQLI, XSS 공격 차단 modsecurity 구성

- back/entry.sh
- back/transcendence/settings.py
- nginx/test
- vault/tools/backrole.sh
- vault/tools/frontrole.sh
- vault/tools/secret.py
- vault/tools/setup.sh
> feat#85 django setting 환경변수 추가

- front/package-lock.json
- front/package.json
- front/src/page/multyGame.js
- front/styles/multyGame.css
> [Fix/#90] gameplay화면 복구

- front/src/page/landing.js
- front/styles/landing.css
> [Fix/#95] Landing page에서만 네비게이션 링크 숨김처리하는 스크립트 추가

- back/localgame/consumers.py
- front/src/page/multyGame.js
- front/styles/multyGame.css
> [Feat/#94] 게임 종료 후 메뉴 복귀 기능 추가

- Makefile
- front/index.html
- front/src/auth/socialLogin.js
- front/src/auth/verifyEmail.js
- front/src/page/changePassword.js
- front/src/page/dashboard_related/friendListAccordion.js
- front/src/page/dashboard_related/greetingBox.js
- front/src/page/dashboard_related/matchHistoryAccordion.js
- front/src/page/dashboard_related/profileAccordion.js
- front/src/page/editProfile.js
- front/src/page/landing.js
- front/src/page/login.js
- front/src/page/multyGame.js
- front/src/page/register.js
- front/src/utils/language.js
***
***
동적으로 번역이 필요한 구간은 하지 않았습니다.
예) matchHistory에서 날짜를 표시하는 부분은 번역이 되지 않았습니다
> feat/#91 다국어 페이지 형성, makefile vault volumes생성 추가

- docker-compose.yaml
- front/src/page/multyGame.js
- front/src/utils/language.js
- front/styles/multyGame.css
> [Fix/#102] game field 스타일 css 수정

- front/src/app.js
- front/src/page/game.js
- front/styles/game.css
***
게임 js 에서 컬러 코드 에러 수정 및 게임관련 파일들 이름의 multygame -> game으로 변경
***
> [Fix/#106] game 관련 이름(함수명,파일명) 변경, js 컬러코드 에러 수정

- front/src/auth/verifyEmail.js
- front/src/page/editProfile.js
- front/src/page/login.js
- front/src/page/register.js
- front/src/utils/language.js
- front/src/vault.js
- front/styles/register.css
> [Fix/#108] 회원가입 - 유저 플로우 수정 / 이메일 인증 - 코드 수정 및 다국어 번역 수정

- front/src/app.js
- front/src/auth/verifyEmail.js
- front/styles/verifyEmail.css
> [Feat/#110] 페이지 이동 시 기존 HTML을 초기화하는 기능 추가

- Makefile
- back/transcendence/settings.py
- front/src/auth/verifyEmail.js
- front/src/page/login.js
- front/src/page/register.js
- front/src/utils/axiosInterceptor.js
- front/src/utils/language.js
- front/src/vault.js
- vault/tools/frontrole.sh
> [Refactor/#112] 회원가입, 로그인 문제 해결 중 중간 저장

- front/index.html
***
***
1. 로그인 버튼일때 클릭 -> 로그인 페이지로 이동
2. 로그인 되어 있을 시 -> 로그인 버튼을 로그아웃 버튼으로 변경
3. 로그아웃 버튼일때 클릭 -> 로그아웃 되며, 버튼은 로그인 버튼이 되고, 랜딩페이지로 리디렉션
> [Fix/#117] 상단 네비게이션 바 로그인/로그아웃 버튼 로직 수정

- front/src/app.js
- front/src/auth/authProvider.js
- front/src/page/login.js
- front/src/utils/axiosInterceptor.js
- front/src/vault.js
> [Feat/#114] 로그인 기능 추가

- front/index.html
- front/src/auth/authProvider.js
- front/src/auth/verifyEmail.js
- front/src/vault.js
- front/styles/verifyEmail.css
> [Fix/#122] index.html 오류 수정, 이메일 인증 페이지 전송 버튼 삭제

- back/accounts/models.py
- back/accounts/serializers.py
- back/accounts/views.py
- back/localgame/consumers.py
- back/social_accounts/serializers.py
- back/social_accounts/utils.py
- front/src/auth/authProvider.js
- front/src/page/editProfile.js
- front/src/page/game.js
- vault/tools/backrole.sh
- vault/tools/setup.sh
> [Feat/#133] 프로필 수정 페이지 기능 추가

- back/entry.sh
- vault/.env
- vault/Dockerfile
- vault/tools/backrole.sh
- vault/tools/frontrole.sh
- vault/tools/setup.sh
> Fix/#136 vault 안정화 작업

- back/localgame/consumers.py
- front/Dockerfile
- front/src/page/game.js
- nginx/nginx.sh
- vault/.env
- vault/tools/setup.sh
> fix/140 vault 생성 로직 수정

- vault/tools/setup.sh
> [HOTFIX] Update setup.sh

- vault/tools/setup.sh
비밀 컨테이너 생성과 AppRole 발급을 최초 1회만 수행하도록 수정
***
***
> [Fix] vault 생성 로직 오류 수정

- vault/tools/setup.sh
> [Fix] vault 생성 로직 오류 수정2

- back/friends/views.py
- front/src/page/dashboard_related/friendListAccordion.js
> [Feat/#142] 친구 목록 생성 및 조회

- back/entry.sh
> fix/#164 마이그레이션 수정

- back/accounts/urls.py
- back/accounts/views.py
- front/src/page/editProfile.js
- front/src/utils/language.js
***
***
views.py에 계정 삭제 view를 만들었고 urls.py에 api url을 추가하여 edit프로필에서 계정삭제를 추가했습니다.
> feat/# 계정삭제 기능 추가
